---
  - name: Create New Gold - vsrx
    hosts: vsrx
    connection: local
    gather_facts: False

    vars:
      timestamp: "{{ hostvars['localhost']['ansible_facts']['date_time']['iso8601_basic_short'] }}"
      connection_details:
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        host: "{{ inventory_hostname }}"

    tasks:
      - junos_command:
          commands: show configuration
          display: set 
        register: config_data

      #- debug: var='\n'.join(config_data.stdout)
      #use to test output of what is being saved

#https://www.mydailytutorials.com/ansible-create-directory/
      - local_action:
          module: file
          path: "/home/lab-admin/lab-configs/{{inventory_hostname}}/gold-config/"
          state: directory

#      - local_action:
#          module: copy
#          src: "/home/lab-admin/lab-configs/{{inventory_hostname}}/gold-config/gold.set"
#          dest: "/home/lab-admin/lab-configs/{{inventory_hostname}}/gold-config/gold-backup-{{ timestamp }}.set"

#https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
      - local_action:
          module: copy
          content: "{{ '\n'.join(config_data.stdout) }}"
          dest: "/home/lab-admin/lab-configs/{{inventory_hostname}}/gold-config/gold.set"
          backup: yes

          #https://www.juniper.net/documentation/en_US/junos-ansible/topics/topic-map/junos-ansible-configuration-loading-committing.html
          #dest: "/home/lab-admin/lab-configs/{{inventory_hostname}}/backup-configs/{{ timestamp }}.conf"
          #use if display:set is commented out

          